export default `Receiver,Richard,Annie,Clancy,Jena,Ruby,Sasha,Digby,Archie,James,Kate,Sam,Lou,WillSr,Rachel,Andrew,Tommy,Nina,WillJr
Richard,false,true,true,true,true,false,false,false,true,true,true,true,true,true,true,false,false,false
Annie,false,false,true,true,true,false,false,false,true,true,true,true,true,true,true,false,false,false
Clancy,true,true,false,true,true,true,true,true,true,true,true,true,true,true,true,false,false,false
Jena,true,true,true,false,false,true,true,true,false,false,false,false,false,false,false,false,false,false
Ruby,true,true,true,false,false,false,true,true,true,true,true,true,true,true,true,false,false,false
Sasha,true,true,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false
Digby,true,true,true,true,true,true,false,true,true,true,true,true,true,true,true,false,false,false
Archie,true,true,true,true,true,true,true,false,true,true,true,true,true,true,true,false,false,false
James,true,true,true,false,true,false,true,true,false,false,true,true,true,true,true,true,true,true
Kate,true,true,true,false,true,false,true,true,false,false,true,true,true,true,true,true,true,true
Sam,true,true,true,false,true,false,true,true,false,false,false,false,true,true,true,false,false,false
Lou,true,true,true,false,true,false,true,true,true,true,false,false,true,true,true,false,false,false
WillSr,true,true,true,false,true,false,true,true,false,false,true,true,false,false,true,true,true,true
Rachelle,true,true,true,false,true,false,true,true,true,true,true,true,false,false,true,true,true,true
Andrew,true,true,true,false,true,false,true,true,false,false,true,true,true,true,false,true,true,true
Tommy,true,true,true,false,true,false,true,true,true,true,false,false,true,true,true,false,false,false
Nina,true,true,true,false,true,false,true,true,true,true,false,false,true,true,true,false,false,false
WillJr,true,true,true,false,true,false,true,true,true,true,false,false,true,true,true,false,false,false`;
